// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteNote(arg1:string):Promise<void>;

export function GetCurrentTime():Promise<number>;

export function LoadNotes():Promise<Array<main.Note>>;

export function SaveAsNote(arg1:string,arg2:string):Promise<Record<string, any>>;

export function SaveNote(arg1:main.Note):Promise<void>;
