// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function GetCurrentTime() {
  return window['go']['main']['App']['GetCurrentTime']();
}

export function LoadNotes() {
  return window['go']['main']['App']['LoadNotes']();
}

export function SaveAsNote(arg1, arg2) {
  return window['go']['main']['App']['SaveAsNote'](arg1, arg2);
}

export function SaveNote(arg1) {
  return window['go']['main']['App']['SaveNote'](arg1);
}
